AWSTemplateFormatVersion: 2010-09-09

# 各種パラメータ
Parameters:
  AccountID:
    Type: String
    Default: ""

# 各種リソース
Resources:

  # ECRのRepositoryを作成
  # リポジトリポリシーに特定のアカウントからのアクセスのみを許可するように設定
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
      RepositoryName: "practice_repository"
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: practiceRepositoryPolicy
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AccountID}:root"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"