AWSTemplateFormatVersion: 2010-09-09

# 各種リソース
Resources:
  UsersPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: UsersPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - 'iam:PutUserPolicy'
              - 'iam:GetRole'
              - 'iam:DeleteRole'
              - 'iam:CreateRole'
              - 'iam:PutRolePolicy'
              - 'iam:DeleteRolePolicy'
              - 'iam:PassRole'
              - 's3:CreateBucket'
              - 's3:PutBucketPublicAccessBlock'
              - 's3:DeleteBucket'
              - 'ecr:SetRepositoryPolicy'
              - 'ecr:CreateRepository'
              - 'ecr:DeleteRepository'
              - 'codestar-connections:*'
              - 'codepipeline:GetPipeline'
              - 'codepipeline:CreatePipeline'
              - 'codepipeline:DeletePipeline'
              - 'codepipeline:GetPipelineState'
              - 'codepipeline:UpdatePipeline'
              - 'codebuild:CreateProject'
              - 'cloudformation:CreateStack'
              - 'cloudformation:UpdateStack'
            Resource: '*'
      Users:
        - koyamaakira

# aws cloudformation update-stack --profile kojin-local --template-body file://./.aws/cfn/iam-policy.yml     --stack-name iam-policy --region ap-northeast-1 --capabilities CAPABILITY_IAM